# Generated by Django 4.1.7 on 2023-06-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_education_user_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Register',
        ),
    ]
